CREATE OR REPLACE TRIGGER PRIORIDAD_PARICIPACION_1
-- COMO COMPRUEBO SIN HAN PARTICIPADO ANTERIORMENTE??
CREATE OR REPLACE TRIGGER PRIORIDAD_PARTICIPACION_2
-- COMO COMPRUEBO SIN HAN PARTICIPADO ANTERIORMENTE??

CREATE OR REPLACE TRIGGER PAGOS_PENDIENTES
BEFORE INSERT ON INSCRIPCIONES
FOR EACH ROW
DECLARE 
pago VARCHAR2;
BEGIN
SELECT (estado) INTO pago FROM RECIBOS
IF (pago = 'pendiente') THEN 
  raise_application_error
  (-20600 || 'El participante tiene pagos pendientes');
  END IF;
  END
  
CREATE OR REPLACE TRIGGER REPRESENTANTE_LEGAL
BEFORE INSERT ON PARTICIPANTES
FOR EACH ROW
DECLARE
nacimiento DATE;
discapacidad NUMBER;
tutor INTEGER;
BEGIN
SELECT (fechaNacimiento) INTO nacimiento FROM PERSONAS
SELECT (gradoDiscapacidad) INTO discapacidad FROM PARTICIPANTES
SELECT (OID_Tut) INTO tutor FROM PARTICIPANTES
IF ((discapacidad>0.5 || comprobarEdad) && OID_Tut = NULL) THEN
raise_application_error
  (-20601 || 'Si el participante es menor de edad o tiene un grado de
  discapacidad superior al 50% debe tener asignado un tutor legal');
  END IF;
  END
  
CREATE OR REPLACE TRIGGER INFORMACION_MEDICA
BEFORE INSERT ON PARTICIPANTES
FOR EACH ROW
DECLARE
informe 


CREATE OR REPLACE TRIGGER PRIORIDAD_VOLUNTARIADO
-- COMO COMPRUEBO SIN HAN PARTICIPADO ANTERIORMENTE??

CREATE OR REPLACE TRIGGER OFERTAS_ACTIVIDADES

CREATE OR REPLACE TRIGGER TRANSMISION_MENSAJES

CREATE OR REPLACE TRIGGER TIPO_PATROCINADOR
AFTER INSERT ON PATROCINIOS
FOR EACH ROW
DECLARE
coste NUMBER;
cantidad NUMBER;
evento INTEGER;
BEGIN
SELECT (costeTotal) INTO coste FROM ACTIVIDADES
SELECT (cantidad) INTO cantidad FROM PATROCINIOS
SELECT (esEvento) INTO evento FROM INSTITUCIONES
IF (coste = cantidad) THEN
UPDATE INSTITUCIONES
    SET tipo  = oro
END IF
END
IF (coste > cantidad && )

CREATE OR REPLACE TRIGGER INFO_DONANTES

CREATE OR REPLACE TRIGGER CUESTIONARIOS
-- DONDE SE REGISTRAN??

CREATE OR REPLACE TRIGGER FINANCIACION_PROYECTOS

CREATE OR REPLACE TRIGGER PLAZAS_PARTICIPANTES
BEFORE INSERT ON INSCRIPCIONES
FOR EACH ROW
DECLARE
plazas INTEGER;


CREATE OR REPLACE TRIGGER PLAZO_VALORACION
BEFORE INSERT ON RESPUESTAS
FOR EACH ROW
DECLARE
fecha DATE;
BEGIN
SELECT (fechaCreacion) INTO fecha FROM CUESTIONARIOS
IF (SYSDATE NOT BETWEEN fecha AND DATEADD(day,15,fecha))
raise_application_error
  (-20602 || 'Solo puede enviar el formulario 15 días después de que este sea creado');
END IF
END

CREATE OR REPLACE TRIGGER GRADO_DISCAPACIDAD
-- HECHO CON CONSTRAINT




